version: "3.1"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - pgadmin4:/metabase-data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  pgadmin4:
  postgres:
